name: Matrix

on: [push]

jobs:
    strategia-Matrix: 
      runs-on: ubuntu-latest

      strategy: #Detecta estrategia Matrix y para este caso ejecuta 3 veces (versiones) ek JOB 
        matrix:
          php-version: [7.4, 8.0, 8.1]
      
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1
        
        - name: SET up PHP
          uses: shivamathur/setup-php@v2 
          with: 
            php-version: ${[matrix.php-version]}

        - name: Run Script 
          run: |
            echo "PHP VERSION ${[matrix.php-version]}"
            php -v
        
    


